### ISSUE TITLE
图片按比例呈现黑科技

### ISSUE THREAD

**Issue by johnsoncheg** [johnsoncheg/johnsoncheg.github.io#30]
```html
<div id="container" class="placeholder">
  < img  />
</div>
```

```css
#container {
  width: 30%;
  position: relative;
  background-color: red;
  overflow: hidden;  //需要触发BFC消除margin折叠的问题
}
.placeholder:after {
  content: '';
  display: block;
  margin-top: 100%; //margin 百分比相对父元素宽度计算
} 
img {
  position: absolute;
  top: 0;
  width: 100%;
}
```
